# Generated by Django 5.2 on 2026-03-17 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус денежного потока')),
            ],
            options={
                'verbose_name': 'Статус денежного потока',
                'verbose_name_plural': 'Статусы денежного потока',
                'db_table': 'cash_flow_statuses',
            },
        ),
        migrations.CreateModel(
            name='CashFlowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип денежного потока')),
            ],
            options={
                'verbose_name': 'Тип денежного потока',
                'verbose_name_plural': 'Типы денежного потока',
                'db_table': 'cash_flow_types',
            },
        ),
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория (подкатегория) денежного потока')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='cash_flow.cashflowcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cash_flow.cashflowtype')),
            ],
            options={
                'verbose_name': 'Категория (подкатегория) денежного потока',
                'verbose_name_plural': 'Категории (подкатегории) денежного потока',
                'db_table': 'cash_flow_categories',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма денежного потока')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='cash_flow.cashflowcategory')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='cash_flow.cashflowstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='cash_flow.cashflowtype')),
            ],
            options={
                'verbose_name': 'Денежный поток',
                'verbose_name_plural': 'Денежные потоки',
                'db_table': 'cash_flows',
                'ordering': ['creation_date'],
            },
        ),
    ]
